import { Inter } from 'next/font/google'
import { Footer } from './components/Footer/Footer'
import { Navigation } from './components/Navigation/Navigation'
import './globals.css'
import { Providers } from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Sheltie', //Esto es lo mismo que utilizar head > title
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className} style={{
                display: 'flex',
                flexDirection: 'column', minHeight: '100vh'
            }}>
                <Providers>
                    <Navigation />
                    <div className={'container'}>
                        {children}
                    </div>
                    <Footer />
                    {/* TODO: Agregar footer que muestre mail de contacto, pais de origen, all rights reserved, logos de algunas redes sociales y las secciones disponibles. */}
                </Providers>
            </body>
        </html >
    )
}
