import './globals.css'
import { Inter } from 'next/font/google'
import { Navigation } from './components/Navigation/Navigation'
import { Providers } from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Sheltie', //Esto es lo mismo que utilizar head > title
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>
                    <Navigation />
                    <div className={'container'}>
                        {children}
                    </div>
                </Providers>
            </body>
        </html>
    )
}
